---
version: '3.9'
services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     # depends_on:
  #     #   - mysql
  #   ports:
  #     - 3000:3000
  #   environment:
  #     # DATABASE_URL: mysql://user:Password123@mysql:3306/testDB
  #     NODE_ENV: development
  #     PORT: 3000
  #   volumes:
  #     - ./src:/app/src

  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql:/data/db
      - mysql_config:/data/configdb
    environment:
      MYSQL_PASSWORD: 'Password123'
      MYSQL_USER: 'user'
      MYSQL_DATABASE: 'testDB'
      MYSQL_ROOT_PASSWORD: 'Password123!'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  mysql: null
  mysql_config: null
